### ISSUE TITLE
libraries

### ISSUE THREAD

**Issue by akaJes** [neoxharsh/ESP8266_NeoPixel_Dashboard#1]
can i suggest for you some simplification for libraries?

instead Simple-Timer (https://github.com/jfturcot/SimpleTimer)
to use builtin Ticker library (it is only single timer and based on system timer and no need run it in loop)
https://github.com/esp8266/Arduino/blob/master/libraries/Ticker/Ticker.h

instead NTPClient (https://github.com/arduino-libraries/NTPClient)
and instead external RTC ic and RTC_By_Makuna (https://github.com/Makuna/Rtc)
also core/embeded code sample like this
```
#include <Arduino.h>
#include <time.h>

  configTime(time_zone * 3600, 0, "pool.ntp.org", "time.nist.gov");
  Serial.println("\nWaiting for time");
  while (!time(nullptr)) {
    Serial.print(".");
    delay(200);
  }
```
https://github.com/esp8266/Arduino/blob/master/tests/device/test_time/test_time.ino
https://github.com/esp8266/Arduino/blob/master/tools/sdk/libc/xtensa-lx106-elf/include/time.h

i'm uisng internal RTC and have good precision in weeks

**Comment by neoxharsh** [comment]
Thanks for the suggestion, I will implement those as soon as possible. Have you built the project?

**Comment by akaJes** [comment]
No, didn't. Just you used mine library

**Comment by akaJes** [comment]
If you insert this additional code
```
Pings[i].on(true,[](const AsyncPingResponse& response){
        return (response.answer);
      });
```
Ping will not wait for another successed answers by default it is 3 times and it take 3 sec

**Comment by neoxharsh** [comment]
Code inserted as suggestion #1
